# Target name in monitor
MONITOR_TARGET=socfpga

# Target name in ASP or FMP
RTOS_TARGET=$(MONITOR_TARGET)_gcc

# ASP souce directory
ASPDIR=../asp

# FMP souce directory
FMPDIR=../fmp_1.3.0
